version: '2'

services:
  jsonbox_dev:
    container_name: jsonbox_dev
    image: 'docker.pkg.github.com/aakashlpin/jsonbox/jsonbox:latest'
    env_file:
      - ~/apps/jsonbox/dev.env
    ports:
      - '4001:3000'

  redis_dev:
    container_name: redis_dev
    image: 'bitnami/redis:latest'
    volumes:
      - /tmp/dev/redis/data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  emailapi_dev:
    container_name: emailapi_dev
    restart: always
    image: 'docker.pkg.github.com/aakashlpin/emailapi/emailapi:dev'
    env_file:
      - ~/apps/emailapi-pipeline/dev.env
    volumes:
      - /tmp:/tmp
    ports:
      - '4000:3000'
    depends_on:
      - jsonbox_dev
      - redis_dev
