version: '2'

networks:
  app-tier:
    driver: bridge

services:
  jsonbox:
    container_name: jsonbox
    build: ~/clones/jsonbox/.
    env_file:
      - ~/apps/jsonbox/.env
    ports:
      - '3001:3000'
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - /tmp/redis/data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  emailapi:
    container_name: emailapi
    restart: always
    build: .
    # image: 'docker.pkg.github.com/aakashlpin/emailapi/emailapi:latest'
    env_file:
      - .env.development.local
    ports:
      - '3000:3000'
    networks:
      - app-tier
    depends_on:
      - jsonbox
      - redis
