version: '2'

services:
  whatsapp:
    container_name: whatsapp
    build: ~/projects/whatsapp-cloud/.
    env_file:
      - ~/projects/whatsapp-cloud/.env

  jsonbox:
    container_name: jsonbox
    build: ~/clones/jsonbox/.
    env_file:
      - ~/apps/jsonbox/.env
    ports:
      - '3001:3000'

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  emailapi:
    container_name: emailapi
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - jsonbox
      - redis
      - whatsapp
