version: '2'

services:
  jsonbox:
    container_name: jsonbox
    build: ~/clones/jsonbox/.
    env_file:
      - ~/apps/jsonbox/.env
    ports:
      - '3001:3000'

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - /tmp/redis/data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  emailapi:
    container_name: emailapi
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - jsonbox
      - redis
