version: '2'

services:
  whatsapp:
    container_name: whatsapp
    image: 'docker.pkg.github.com/aakashlpin/whatsapp/whatsapp:latest'
    env_file:
      - ~/apps/whatsapp/.env

  jsonbox:
    container_name: jsonbox
    image: 'docker.pkg.github.com/aakashlpin/jsonbox/jsonbox:latest'
    env_file:
      - ~/apps/jsonbox/.env
    ports:
      - '3001:3000'

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - /tmp/redis/data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  emailapi:
    container_name: emailapi
    restart: always
    image: 'docker.pkg.github.com/aakashlpin/emailapi/emailapi:latest'
    env_file:
      - ~/apps/emailapi-pipeline/docker.env
    volumes:
      - /tmp:/tmp
    ports:
      - '3000:3000'
    depends_on:
      - jsonbox
      - redis
      - whatsapp
