export const RULE_TYPE = {
  INCLUDE_ROWS: 'INCLUDE_ROWS',
  INCLUDE_CELLS: 'INCLUDE_CELLS',
};

export const CELL_MATCH_TYPE = {
  NOT_EMPTY: 'NOT_EMPTY',
  STARTS_WITH: 'STARTS_WITH',
  ENDS_WITH: 'ENDS_WITH',
  EQUALS: 'EQUALS',
  CONTAINS: 'CONTAINS',
  REGEX: 'REGEX',
};

export const TEMPLATE_TYPE = {
  ZERODHA_CN: 'ZERODHA_CN',
  CUSTOM: 'CUSTOM',
};
