name: stage

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.18
      uses: actions/setup-node@v1
      with:
        node-version: '12.18'

    - name: Install yarn
      run: |
        yarn
      env:
        CI: true

    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: aakashlpin/emailapi/emailapi
        registry: docker.pkg.github.com
        username: ${{ secrets.GITBUH_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile-prod
        tags: dev

    - name: Remote Pull docker image of emailapi
      uses: appleboy/ssh-action@master
      env:
        GITBUH_USERNAME: ${{ secrets.GITBUH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.SSH_ID_RSA }}
        envs: GITBUH_USERNAME, GITHUB_TOKEN
        script: |
          docker login docker.pkg.github.com -u $GITBUH_USERNAME -p $GITHUB_TOKEN
          cd ~/apps/emailapi-pipeline && docker-compose -f docker-compose-dev.yml pull

    - name: Remote Start docker server
      uses: appleboy/ssh-action@master
      env:
        GITBUH_USERNAME: ${{ secrets.GITBUH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.SSH_ID_RSA }}
        envs: GITBUH_USERNAME, GITHUB_TOKEN
        script: |
          cd ~/apps/emailapi-pipeline && docker-compose up -f docker-compose-dev.yml --detach --build emailapi_dev
